### ISSUE TITLE
Compilation issue on armv7

### ISSUE THREAD

**Issue by rdeaton** [gebi/libowfat#1]
```
pi@tau:~/libowfat $ make
gcc -c buffer/buffer_putflush.c -pipe -W -Wall -Wextra -O2 -fomit-frame-pointer -D_REENTRANT  -I.
buffer/buffer_putflush.c: In function ‘buffer_putflush’:
buffer/buffer_putflush.c:24:14: error: ‘write’ undeclared (first use in this function)
   if (b->op==write) {
              ^
buffer/buffer_putflush.c:24:14: note: each undeclared identifier is reported only once for each function it appears in
GNUmakefile:153: recipe for target 'buffer_putflush.o' failed
```

Going back to commit 244fd60e751432c7420c7e1e798432600fbf0dda seems to work okay.

**Comment by gebi** [comment]
Thx for taking the time and reporting the issue.

I've updated the mirror to the lastest upstream cvs version, please retry.

After the update it seems to compile fine here with gcc version 4.9.2 both with and without dietlibc.

    $ make
    ...
    /usr/bin/diet -Os gcc -c buffer/buffer_putflush.c -pipe -W -Wall -Wextra -O2 -fomit-frame-pointer -D_REENTRANT  -I.

and

    $ make DIET=
    ...
    gcc -c buffer/buffer_putflush.c -pipe -W -Wall -Wextra -O2 -fomit-frame-pointer -D_REENTRANT  -I.
