### ISSUE TITLE
0.32 error

### ISSUE THREAD

**Issue by 1265578519** [gebi/libowfat#3]
[root@cdn opentracker]# make
cc -o opentracker opentracker.o trackerlogic.o scan_urlencoded_query.o ot_mutex.o ot_stats.o ot_vector.o ot_clean.o ot_udp.o ot_iovec.o ot_fullscrape.o ot_accesslist.o ot_http.o ot_livesync.o ot_rijndael.o -L../libowfat -lowfat -pthread -lpthread -lz
../libowfat/libowfat.a(socket_accept6.o): In function `socket_accept6':
socket_accept6.c:(.text+0x7b): undefined reference to `__builtin_bswap16'
socket_accept6.c:(.text+0xee): undefined reference to `__builtin_bswap16'
../libowfat/libowfat.a(socket_recv6.o): In function `socket_recv6':
socket_recv6.c:(.text+0xa9): undefined reference to `__builtin_bswap16'
socket_recv6.c:(.text+0x125): undefined reference to `__builtin_bswap16'
../libowfat/libowfat.a(socket_send6.o): In function `socket_send6_flag':
socket_send6.c:(.text+0xb7): undefined reference to `__builtin_bswap16'
../libowfat/libowfat.a(socket_bind6.o):socket_bind6.c:(.text+0xa0): more undefined references to `__builtin_bswap16' follow
collect2: ld returned 1 exit status
make: *** [opentracker] Error 1
[root@cdn opentracker]#

**Comment by gebi** [comment]
hi,

thx for reporting this, though this repo is only a mirror of the upstream repo i use/need because upstream still uses cvs.

I'm sorry but i can't provide support for libowfat here. Please report those things to upstream https://www.fefe.de/libowfat/

have a nice weekend.

**Comment by 1265578519** [comment]
我找到了编译安装错误问题所在，，，不同的操作系统需要安装对应的版本，所以在centos6下安装0.32发生了编译错误，需要正确安装0.31
centos6对应0.31
centos7对应0.32
虽然安装过程会发生少许警告提示，但是不影响正常安装完成

**Comment by gebi** [comment]
thx for reporting, but this code is only here for reference, pls report to upstream.
